### ISSUE TITLE
README

### ISSUE THREAD

**Issue by henry-proj** [systemime/Vbox#1]
README看的一脸懵逼。到最后也不知道怎么才能启动。

**Comment by systemime** [comment]
项目还没更新完，如果想试试的话可以先安装这些requirement.txt
<https://github.com/systemime/Vbox/blob/master/requirement.txt>
里的组件，然后搭建kubernetes集群，记得安装coredns和Metrics Server。
获取集群身份认证token，修改Vbox/setting里面token配置，先启动celery，然后启动django就可以了

半夏紫苏 <notifications@github.com> 于2020年5月21日周四 下午12:03写道：
